version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    #projectname-server
    container_name: aep-project-server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - "./server:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=AEPProject"
      LOG_LEVEL: 'debug'
      APP_ENV: 'dev'
      DATABASE_URL: 'postgresql://postgres:testingpass@postgres:5432/db?serverVersion=13&charset=utf8'

  ###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    container_name: aep-project-postgres
    ports:
      - "5433:5432"
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 'testingpass'
    volumes:
      - aep-project-db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  aep-project-db-data:
  ###< doctrine/doctrine-bundle ###
